name: Deploy to Staging

on:
  push:
    branches: [develop]

env:
  DATABASE_URL: ${{ secrets.STAGING_DATABASE_URL }}
  NODE_ENV: production

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Build Docker image
        run: |
          docker build -t velvetmx/velvet-mx:${{ github.sha }} .
          docker tag velvetmx/velvet-mx:${{ github.sha }} velvetmx/velvet-mx:staging
      - name: Push to registry
        run: |
          echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push velvetmx/velvet-mx:staging
      - name: Deploy to k8s
        run: |
          kubectl config use-context ${{ secrets.K8S_CONTEXT_STAGING }}
          kubectl set image deployment/velvet-mx-app app=velvetmx/velvet-mx:staging -n velvet-mx
          kubectl rollout status deployment/velvet-mx-app -n velvet-mx
