apiVersion: v1
kind: ConfigMap
metadata:
  name: velvet-mx-config
  namespace: velvet-mx
data:
  NEXTAUTH_URL: "https://velvetmx.com"
  REDIS_URL: "redis://velvet-mx-redis:6379"
  NODE_ENV: "production"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: velvet-mx-pvc
  namespace: velvet-mx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
