apiVersion: v1
kind: Secret
metadata:
  name: velvet-mx-secrets
  namespace: velvet-mx
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@velvet-mx-db:5432/velvet_mx?schema=public"
  POSTGRES_PASSWORD: "CHANGE_ME"
  NEXTAUTH_SECRET: "CHANGE_ME"
