apiVersion: v1
kind: Secret
metadata:
  name: velvet-mx-secrets
  namespace: velvet-mx
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:CHANGE_ME@postgres.velvet-mx.svc.cluster.local:5432/velvet_mx"
  NEXTAUTH_SECRET: "CHANGE_ME_WITH_RANDOM_SECRET_32_CHARS"
  STRIPE_SECRET_KEY: "sk_test_placeholder"
---
apiVersion: v1
kind: Secret
metadata:
  name: velvet-mx-db-secrets
  namespace: velvet-mx
type: Opaque
stringData:
  POSTGRES_PASSWORD: "CHANGE_ME_WITH_STRONG_PASSWORD"
