apiVersion: v1
kind: Service
metadata:
  name: velvet-mx-app
  namespace: velvet-mx
  labels:
    app.kubernetes.io/name: velvetmx
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: velvetmx
    app.kubernetes.io/component: app
---
apiVersion: v1
kind: Service
metadata:
  name: velvet-mx-db
  namespace: velvet-mx
  labels:
    app.kubernetes.io/name: velvetmx
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: velvetmx
    app.kubernetes.io/component: db
---
apiVersion: v1
kind: Service
metadata:
  name: velvet-mx-redis
  namespace: velvet-mx
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
